version: '3.8'
services:
  web-app:
    container_name: springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=17021972
      - POSTGRES_USER=postgres
      - POSTGRES_DB=spring_app